name: unisba_sisfo2
description: Sisfo Project 2022.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  page_transition: ^2.0.9
  dio: ^4.0.6
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  badges: ^2.0.3
  circular_bottom_navigation: ^2.2.0
  cached_network_image: ^3.0.0
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Segoe
      fonts:
        - asset: assets/fonts/segoe.ttf
        - asset: assets/fonts/segoe_italic.ttf
          style: italic
  
